### ISSUE TITLE
Choose a license for this project. 

### ISSUE THREAD

**Issue by mrjones** [mrjones/Chrome-Arduino#4]
Two different people asked this week about a license.  I hadn't picked one previously for various reasons, but now it's time.

Currently I'm leaning towards GPLv2:
- This seems to align best with the Arduino philosophy (e.g. Arduino IDE is GPLv2).
- Selfishly: I put a lot of time into this project, and I'd love to see future improvements made available.

However, I'd be willing to consider alternatives before making a final decision.  So here's a place to to discuss it (if anyone cares to).

I'll leave discussion open for a week or so (unless there's a clear answer sooner than that).

@durkie @Comingle

**Comment by durkie** [comment]
Hey Matt -- sorry for the confusion, but I'm actually with Comingle and would be doing a lot of the contributions to this repo through either them or myself. I contacted you on twitter initially, but then noticed you weren't super active on there so then tried via pull request/github.

We would love to see this officially open-sourced as well. Open source is part of our philosophy at Comingle (www.comingle.io -- warning: NSFW), and we depend heavily on open-source software and want to contribute back to it as much as we can.

And aside from our interest in the project, it's really great work that you've done so far, and for sure it should be out there for others to benefit from as well.

**Comment by mrjones** [comment]
After weighing things, I've chosen MPL.

This seems to capture the aspects of the GPL that I care most about (that improvements and modifications to this library are made available), but it's more permissive in areas that I don't feel as strongly about (specifically, the MPL would allow this code to be packaged into a larger project that's differently (or not) open sourced.  As long as the the MPL'd files stay under MPL, additional files in the project can be released under any (or no) license).

I'll update the source to reflect this now.

**Comment by mrjones** [comment]
Resolved via 8e86108d399278debcfd3114c671dfdb8f79ea0a and 7b4c45c34669f28ca85027ff4fb2c0b7e6e2a97c .
